// export const CONSTANTS = {
//   FETCH_POSTS,
//   FETCH_POSTS_SUCCESS,
//   FETCH_POSTS_FAILURE,
//   EDIT_POST
// }

export const FETCH_POSTS = 'FETCH_POSTS'
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const EDIT_POST = 'EDIT_POST';
// export const EDIT_POST_SUCCESS = 'EDIT_POST_SUCCESS';
// export const EDIT_POST_FAILURE = 'EDIT_POST_FAILURE';